### ISSUE TITLE
 add multiple file in one zip?

### ISSUE THREAD

**Issue by kingrupam** [moncefplastin07/deno-zip#2]
how to add multiple file in one zip?

**Comment by moncefplastin07** [comment]
Currently the module does not support compression files to zip functionality it's only for ZIP file decompressing, We will add the file compression feature in the next release based on external plugins built in rust for better performance

**Comment by kingrupam** [comment]
great, please add both single file to zip and most important multiple files to zip.

if possible then add aes encryption and decryption For zip file.

**Comment by markthree** [comment]
@kingrupam you can use [nzip](https://github.com/markthree/nzip#program)
