### ISSUE TITLE
Windows decompress does not work with paths with spaces

### ISSUE THREAD

**Issue by lewisandrew** [moncefplastin07/deno-zip#5]
Replace all spaces with backtick and space before using as an argument to Powershell's Expand-Archive (see https://stackoverflow.com/a/18537344).

Snippet:

```JS
import { resolve } from 'https://deno.land/std/path/mod.ts';

const zipSourcePath = resolve('zip with spaces.zip');
const destinationPath = resolve('destination with spaces');
console.log('source', zipSourcePath);
console.log('destination', destinationPath);

const { success: result1 } = await Deno.run({
  cmd: [
    'PowerShell',
    'Expand-Archive',
    '-Path',
    zipSourcePath,
    '-DestinationPath',
    destinationPath,
  ],
  stdout: 'piped',
  stderr: 'piped',
}).status();

const { success: result2 } = await Deno.run({
  cmd: [
    'PowerShell',
    'Expand-Archive',
    '-Path',
    zipSourcePath.replaceAll(' ', '` '),
    '-DestinationPath',
    destinationPath.replaceAll(' ', '` '),
  ],
  stdout: 'piped',
  stderr: 'piped',
}).status();

console.log('Before succeed?', result1); // output: 'After succeed? false'
console.log('After succeed?', result2); // output: 'After succeed? true'
```

**Comment by lewisandrew** [comment]
I've found that it would be more correct to actually wrap the path arguments in quotes, and that escapes all of the characters, including things like `&`. So like

```JS
const cmd = [
    'PowerShell',
    'Expand-Archive',
    '-Path',
    `"${zipSourcePath}"`,
    '-DestinationPath',
    `"${destinationPath}"`,
  ],
```

**Comment by moncefplastin07** [comment]
Thank you for your interest ❤. Yes, this is already happening. I just didn't notice .. make pull request if you want

**Comment by Swifter1243** [comment]
Hey still getting this issue, above are my file paths.
![image](https://user-images.githubusercontent.com/61858676/170214338-11ea36ef-4664-4032-b10f-05cfe6402d2e.png)

**Comment by Swifter1243** [comment]
So if I add quotes to these paths, it works. But the same case is not for the `archiveName`, it crashes no matter if I have quotes or not :/

**Comment by markthree** [comment]
@Swifter1243 @lewisandrew you can use [nzip](https://github.com/markthree/nzip#program)
