### ISSUE TITLE
unZipFromFile seems to not resolve the promise

### ISSUE THREAD

**Issue by bjesuiter** [moncefplastin07/deno-zip#7]
Current Situation: unZipFromFile seems not to resolve the promise. 

My part of the core: 

```
const kiaUnzip = await startKia(`Unzip ${updateZip}`);
  const result = await unZipFromFile(updateZip, ".");
  if (!result) throw new Error(`Zip Extraction failed!`);
  await kiaUnzip.succeed(`Unzipped ${updateZip}`);

  const kiaZipDelete = await startKia(`Remove ${updateZip}`);
  await Deno.remove(updateZip);
  await kiaZipDelete.succeed(`Removed ${updateZip}`);
```

The output:   
`⠧ Unzip vscode-update.zip`

But it should go on and delete the update zip file. 

Do you have any idea what could be wrong there?

**Comment by moncefplastin07** [comment]
It seems that you are using an old version, try to use the latest version and let us know if you will encounter the same problem

**Comment by bjesuiter** [comment]
Thanks for looking into it! 
It was an old version! For some reason I had trusted the google search to give me the newest version, but this was obviously a bad idea :D
